import React from 'react';
import { ShieldAlert, FileText, CheckCircle2, AlertTriangle, Stethoscope } from 'lucide-react';

export default function TermsAndConditions({ setActiveTab }) {
  return (
    <div style={{ width: '100%', maxWidth: '900px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '24px', paddingBottom: '40px' }}>
      
      {/* Header */}
      <div style={{ textAlign: 'center', marginTop: '10px' }}>
        <span className="badge badge-low" style={{ marginBottom: '6px' }}>
          <FileText size={14} /> TERMS OF SERVICE
        </span>
        <h1 style={{ fontSize: '2.2rem', color: 'var(--text-main)', fontWeight: 800 }}>
          Terms and Conditions
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', maxWidth: '600px', margin: '0 auto' }}>
          Standard platform usage terms, veterinary screening disclaimers, and rescue dispatch operational guidelines.
        </p>
        <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '6px' }}>
          Effective Date: October 7, 2026 | Custom Domain: <strong>dermascan.org</strong>
        </div>
      </div>

      <div className="glass-panel" style={{ padding: '32px', borderRadius: '16px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
        
        {/* Critical Veterinary Disclaimer Box */}
        <div style={{
          background: 'var(--medium-bg)',
          border: '1px solid rgba(217, 119, 6, 0.35)',
          borderRadius: '12px',
          padding: '18px',
          display: 'flex',
          alignItems: 'flex-start',
          gap: '12px'
        }}>
          <Stethoscope size={22} color="var(--medium)" style={{ flexShrink: 0, marginTop: '2px' }} />
          <div>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-main)', fontWeight: 800, marginBottom: '4px' }}>
              CRITICAL VETERINARY TRIAGE DISCLAIMER
            </h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.55 }}>
              DermaScan provides automated dermatological preliminary screening intended solely to prioritize emergency rescue dispatch. Results generated by the platform do NOT constitute a formal, binding veterinary diagnosis and should never replace direct clinical evaluation, skin scraping cultures, or prescribed treatment by a licensed veterinary doctor.
            </p>
          </div>
        </div>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <CheckCircle2 size={18} color="var(--primary)" />
            1. Acceptance of Terms
          </h2>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
            By accessing or using the platform hosted at <strong>dermascan.org</strong>, users agree to be bound by these Terms and Conditions. If you do not agree with any portion of these terms, you should discontinue platform usage immediately.
          </p>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <AlertTriangle size={18} color="var(--primary)" />
            2. User Responsibilities & Reporting Integrity
          </h2>
          <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
            <ul style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li>
                <strong>Factual Reporting:</strong> Users submitting stray animal incident reports agree to provide truthful location details, accurate visible symptom descriptions, and authentic photographs.
              </li>
              <li>
                <strong>No False Emergencies:</strong> Submitting fraudulent emergency SOS dispatches or misleading location pins is strictly prohibited and will result in IP blocklisting.
              </li>
              <li>
                <strong>Safety Distance:</strong> Citizen reporters must maintain a safe physical distance from distressed or injured animals while capturing photographs to prevent injury or transmission risks.
              </li>
            </ul>
          </div>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          <h2 style={{ fontSize: '1.25rem', color: 'var(--text-main)', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <ShieldAlert size={18} color="var(--primary)" />
            3. Limitation of Liability
          </h2>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
            DermaScan, its engineering developers, and affiliate rescue organizations shall not be held liable for injuries, delayed NGO field responses, misidentifications resulting from poor photograph lighting/focus, or independent animal handler interventions.
          </p>
        </section>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '10px', borderTop: '1px solid var(--border-color)', paddingTop: '16px' }}>
          <h2 style={{ fontSize: '1.1rem', color: 'var(--text-main)', fontWeight: 700 }}>
            4. Governance & Domain Verification
          </h2>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
            These terms are governed in accordance with applicable animal welfare laws. All official operations are hosted exclusively on verified custom domain <strong>dermascan.org</strong>.
          </p>
        </section>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '10px' }}>
          <button 
            className="btn-primary" 
            onClick={() => setActiveTab('home')}
            style={{ padding: '10px 24px', borderRadius: '8px' }}
          >
            Back to Home
          </button>
        </div>

      </div>

    </div>
  );
}
